config/routes.rb
Rails.application.routes.draw do
  root to: 'stats#index'
  resources :users
  resources :teams
  resources :games
  resources :matches
  resources :game_histories, only: [:index]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :teams

  def to_s
    first_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name

  .form-actions
    = f.button :submit, class: 'green'

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/destroy.html.slim
h1 Users#destroy
p Find me in app/views/users/destroy.html.slim

app/views/users/edit.html.slim
.row
  .col.m10.offset-m1.s12
    h1 Editing user

    == render 'form'

    = link_to 'Show', @user
    '|
    = link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table.striped
  thead
    tr
      th First Name
      th Last Name
      th Action

  tbody
    - @users.each do |user|
      tr
        td = user.first_name
        td = user.last_name
        td
          = link_to user, class: 'btn btn-floating blue user-action' do
            i.material-icons visibility
          = link_to edit_user_path(user), class: 'btn btn-floating blue user-action' do
            i.material-icons edit
          = link_to user, data: {:confirm => 'Are you sure?'}, :method => :delete,  class: 'btn btn-floating red user-action' do
            i.material-icons delete

br

= link_to 'New User', new_user_path, class: 'btn green white-text'

app/views/users/new.html.slim
.row
  .col.m10.offset-m1.s12
    h1 New user

    == render 'form'

    br
    = link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

= @user.first_name
= @user.last_name

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path

app/views/users/update.html.slim
h1 Users#update
p Find me in app/views/users/update.html.slim