config/routes.rb
Rails.application.routes.draw do
  root to: 'stats#index'
  resources :users
  resources :teams
  resources :games
  resources :matches
  resources :game_histories, only: [:index]
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :team1, class_name: Team, foreign_key: "team1_id"
  belongs_to :team2, class_name: Team, foreign_key: "team2_id"
  belongs_to :winning_team, class_name: Team, foreign_key: "winning_team_id"

  validates :team1, :team2, presence: true
  validates :score_team1, :score_team2,
    numericality: { greater_than: 0, less_than: 11, message: "Score must be in 0-10"}

  before_save :update_winning_team_id

  # Public: Return all game that doesn't belongs to a match
  #
  # Example
  #
  #   Game.single
  #
  # Return
  #   An array of games
  def self.single
    joins("LEFT JOIN matches_games ON matches_games.game_id = games.id")
      .where("matches_games.match_id IS NULL")
  end

  # Internal: Update winning team id for game model
  #   It's a cache field, help finding the winner faster
  #
  #   This method will be trigger when a game is saved (create or update)
  #
  #   The winning_team_id is only updated when score reach to 10
  #
  # Example
  #
  #   Manually usage
  #
  #     game.update_winning_team_id
  #
  #   Automatically use
  #
  #     game.score_team1 = 10
  #     game.score_team2 = 9
  #     game.save! # => set the winning_team_id = team1_id
  def update_winning_team_id
    return unless score_team1 == 10 || score_team2 == 10
    if score_team1 > score_team2
      self.winning_team_id = team1_id
    elsif score_team2 > score_team1
      self.winning_team_id = team2_id
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params[:game].permit(:team1_id, :team2_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.slim
= simple_form_for(@game) do |f|
  = f.error_notification

  .form-inputs
    = f.input :team1_id, collection: Team.all
    = f.input :score_team1
    = f.input :team2_id, collection: Team.all
    = f.input :score_team2

  .form-actions
    = f.button :submit

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'|
= link_to 'Back', games_path

app/views/games/index.html.slim
h1 Listing games

table
  thead
    tr
      th ID
      th Team1
      th Score Team1
      th Team2
      th Score Team2
      th
      th

  tbody
    - @games.each do |game|
      tr
        td = game.created_at.strftime("%d %b, %g:%M")
        td = game.team1
        td = game.score_team1
        td = game.team2
        td = game.score_team2
        td = link_to 'Show', game
        td = link_to 'Edit', edit_game_path(game)
        td = link_to 'Destroy', game, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Game', new_game_path

app/views/games/new.html.slim
h1 New game

== render 'form'

= link_to 'Back', games_path

app/views/games/show.html.slim
p#notice = notice


= link_to 'Edit', edit_game_path(@game)
'|
= link_to 'Back', games_path