config/routes.rb
Rails.application.routes.draw do
  root to: 'stats#index'
  resources :users
  resources :teams
  resources :games
  resources :matches
  resources :game_histories, only: [:index]
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_and_belongs_to_many :games, join_table: "matches_games"
  belongs_to :winning_team, foreign_key: "winning_team_id", class_name: Team

  belongs_to :team1, class_name: Team, foreign_key: "team1_id"
  belongs_to :team2, class_name: Team, foreign_key: "team2_id"

  validates_length_of :games, maximum: 3

  accepts_nested_attributes_for :games

  before_save :update_winning_team_id

  # Internal: Update winning team id
  #   It's a caching column to keep track the winner team for each match
  #
  #   A match requires at least 2 games
  #   If a team wins 2 games, consider they are win, it works for both 3 & 2 games
  #   If the number of winning & losing are same, can't define the winner yet (for 2 games case)
  #
  #   Will be triggered when match is save (create or update)
  #
  # Example
  #
  #    Manually update:
  #      match.update_winning_team_id
  #
  #    Update by save
  #      match.games.create(game_params) # create a game
  #      match.save
  def update_winning_team_id
    return if games.size < 2

    winning_team_ids = games.pluck(:winning_team_id)

    if winning_team_ids.count(team1_id) > winning_team_ids.count(team2_id)
      self.winning_team_id = team1_id
    elsif winning_team_ids.count(team1_id) < winning_team_ids.count(team2_id)
      self.winning_team_id = team2_id
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all.includes(:games)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
    @match.games.build
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    @match.games.each do |game|
      game.team1 = @match.team1
      game.team2 = @match.team2
    end

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_path, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @match.assign_attributes(match_params)

    @match.games.each do |game|
      game.team1 = @match.team1
      game.team2 = @match.team2
    end

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_path, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:team1_id, :team2_id, games_attributes: [:id, :score_team1, :score_team2])
    end
end

app/views/matches/_form.html.slim
= simple_form_for(@match) do |f|
  = f.error_notification

  .form-inputs
    = f.input :team1_id, collection: Team.all
    = f.input :team2_id, collection: Team.all
    br
    = f.simple_fields_for :games do |game|
      .duplicatable_nested_form
        .card
          .card-content
            .card-title.grey-text Game
            = render 'game_fields', f: game
    = link_to 'Add another game', '#', class: 'add-nested-form'

  .form-actions
    = f.button :submit

app/views/matches/_game_fields.html.slim
= f.input :score_team1
= f.input :score_team2
- if f.object.new_record?
	= link_to 'Remove', '', :class => 'destroy_duplicate_nested_form'
- else
	= link_to 'Remove', game_path(f.object), :method => :delete, :remote => true, :class => 'destroy_duplicate_nested_form'
	= f.input :id, as: :hidden

app/views/matches/edit.html.slim
h1 Editing match

== render 'form'

= link_to 'Show', @match
'|
= link_to 'Back', matches_path

app/views/matches/index.html.slim
h1 Listing matches

table.highlight
  thead
    tr
      th Games
      th Scores
      th Winner
      th
      th

  tbody
    - @matches.each do |match|
      tr
        td = match.games.size
        td
          ul.collection
            - match.games.each do |game|
              li.collection-item
                p
                  = link_to "#" do
                    span.chip{class = "#{'yellow white-text' if game.team1.id == game.winning_team_id}"}
                      = game.team1
                    span.badge= game.score_team1
                p
                  = link_to "#" do
                    span.chip{class = "#{'yellow white-text' if game.team2.id == game.winning_team_id}"}
                      = game.team2
                    span.badge= game.score_team2

        td
          - if match.winning_team
            span.chip.red.white-text= match.winning_team

        td
          = link_to match, class: "btn btn-floating blue user-action" do
            i.material-icons visibility
          = link_to edit_match_path(match), class: "btn btn-floating blue user-action" do
            i.material-icons edit
          = link_to match_path(match), method: :delete, confirm: "Are you sure?", class: "btn btn-floating red user-action" do
            i.material-icons delete

br

= link_to 'New Match', new_match_path

app/views/matches/new.html.slim
h1 New match

== render 'form'

= link_to 'Back', matches_path

app/views/matches/show.html.slim
p#notice = notice


= link_to 'Edit', edit_match_path(@match)
'|
= link_to 'Back', matches_path